### ISSUE TITLE
gui implementation in pygame

### ISSUE THREAD

**Issue by xcodz-dot** [xcodz-dot/denver#1]
anyone who would like to contribute can make a pull request

**Comment by AdeshChoudhar19** [comment]
What we have to do?

**Comment by xcodz-dot** [comment]
well, we have to make a GUI interface library the one like PGU library, also we need this because that library is old and we need a well documented library, if you are any good in pygame then please help me.

@AdeshChoudhar19

**Comment by AdeshChoudhar19** [comment]
Yes, I have made some basic games using pygame. If you can guide me, then I'm good to go.

**Comment by xcodz-dot** [comment]
Ok, good. Basic Gaming is enough to make pygame gui
* You can simply create a module named `pgui.py` under package `denver`
* Make a class named somewhat master (A class that holds other sub-gui widgets, handles event loops, fps loops)
 Well master class can contain somewhat these functions:

```python
import pygame

class gui_window: #MasterClass
    def __init__(self, width, height):
        self.dimensions = (width, height)
        self.display = pygame.display.set_mode(self.dimensions)
        self.clock = pygame.time.Clock()
        self.clock_fps = 60
        self.childs = []
    def update(self):
        self.clock.tick(self.clock_fps)
        for child in self.childs:
            child.draw(self.display)
    def add(self, child):
        self.childs.append(child)

```

**Comment by xcodz-dot** [comment]
In the above statment you can add event loop in update method (Content of while loop to that)

You can add more methods to class, etc

SubGui Widget should be somewhat like that
```python
class sub_gui_widget: #You can modify this to make it a button, label, etc
    def __init__(self, width, height, spec1, spec2, spec3 ...):
        self.surface = pygame.Surface((width, height))
    def draw(self, master_display):
        # draw things on self.surface
        master_display.blit(self.surface)
        self.surface.fill((255,255,255)) #Reset Your Surface
```

**Comment by xcodz-dot** [comment]
spec1, spec2, spec3 are the extra arguments. Shall i assign this issue to you?

**Comment by AdeshChoudhar19** [comment]
I'll try my best.

**Comment by xcodz-dot** [comment]
All the best, thank you

**Comment by xcodz-dot** [comment]
how is it going @AdeshChoudhar19? (I am a little curious 😄)

**Comment by AdeshChoudhar19** [comment]
I'm trying to learn, this is a new topic for me. Please give me some more time.

**Comment by xcodz-dot** [comment]
no problems, take your time 😄  (I have tried it myself and it took lots of brainwork and mathmatics to make look good but i eventually stopped it after i was not able to fix mouse buttons)

**Comment by AdeshChoudhar19** [comment]
@xcodz-dot I started working on this issue but nowadays I'm not getting enough time. I appreciate your kindness, but I think I will not be able to do this soon, due to college exams and assignments. You can assign someone else who is interested. I will not be able to do anything for 1 month from now, so you may unassign me if you want this done urgently, I hope you understand. Thanks for your patience.

**Comment by xcodz-dot** [comment]
its ok sir, exams are more important this is my hobby to write code. Well to inform you, i am also having exams, i am actually studying in a school and i am way smaller than you. thanks for your trial. I appreciate it 😄. You may take as much time you want.

@AdeshChoudhar19

**Comment by AdeshChoudhar19** [comment]
Sir!:smile: Call me Adesh, please. So nice of you to understand the situation. I will definitely continue to work on this as and when I will get some time. Thanks, @xcodz-dot.

**Comment by xcodz-dot** [comment]
Hello @AdeshChoudhar19, Are you free now?
