### ISSUE TITLE
Code Compatibility with Python 2.7+, Python 3.7+

### ISSUE THREAD

**Issue by xcodz-dot** [xcodz-dot/denver#12]
If Anyone is good at this work may log a pull request

**Comment by cclauss** [comment]
Python 2 died on 1/1/2020 so why support unsupported software?
https://devguide.python.org/#status-of-python-branches
https://devguide.python.org/devcycle/#end-of-life-branches

**Comment by xcodz-dot** [comment]
OK then, we will not support that
