### ISSUE TITLE
Code compatibility with PEP8

### ISSUE THREAD

**Issue by xcodz-dot** [xcodz-dot/denver#14]
Anyone looking forward to modify files with PEP8 are welcome, be sure all the reference to function_call or variable you are going to edit are not broken.

**Comment by cclauss** [comment]
Just run `python3 -m pip install black ; black ." To autofix most PEP8 issues.
https://github.com/psf/black/blob/master/README.md

**Comment by cclauss** [comment]
I do not need to be a maintainer of this repo.  I will submit pull requests and you can accept or reject them.

**Comment by xcodz-dot** [comment]
ok then
thanks
