### ISSUE TITLE
Typos should be fixed

### ISSUE THREAD

**Issue by cclauss** [xcodz-dot/denver#18]
From codespell like #4
```
./denver/crypt.py:3: usefull ==> useful
./denver/crypt.py:185: ceasar ==> caesar
./denver/crypt.py:201: ceasar ==> caesar
./denver/text.py:2: usefull ==> useful
./denver/datau.py:5: Handeling ==> Handling
./denver/datau.py:7: completly ==> completely
./denver/bdtp.py:261: Recieved ==> Received
./scripts/test_server.py:10: Adress ==> Address
```

**Comment by xcodz-dot** [comment]
will fix it soon

**Comment by cclauss** [comment]
Once this is done, remove `|| true` from this line which will make all future typos fail the GitHub Action.
https://github.com/xcodz-dot/denver/blob/master/.github/workflows/lint_python.yml#L26

**Comment by xcodz-dot** [comment]
ok, will initiate the push tommorow, i will post a new repository on github, (Empty, with a base, for development)

**Comment by xcodz-dot** [comment]
Done
