### ISSUE TITLE
Why is code duplicated in this repo?

### ISSUE THREAD

**Issue by cclauss** [xcodz-dot/denver#6]
1. https://github.com/xcodz-dot/denver/blob/master/denver/graphics3d.py
2. https://github.com/xcodz-dot/denver/blob/master/build/lib/denver/graphics3d.py
3. https://github.com/xcodz-dot/denver/blob/master/installer_info/denver/graphics3d.py
should be one file, not three.

**Comment by xcodz-dot** [comment]
sorry for inconvenience,

build/lib/graphics3d.py was generated by the python setup.py
installer_info/denver/graphics3d was made due to internal testing on my platform

Those are now deleted, any pull requests are welcome
