### ISSUE TITLE
Doctests are failing

### ISSUE THREAD

**Issue by cclauss** [xcodz-dot/denver#9]
https://github.com/xcodz-dot/denver/runs/1172186210?check_suite_focus=true#step:10:18

**Comment by xcodz-dot** [comment]
I will be fixing the doctests

**Comment by xcodz-dot** [comment]
Please check if the code edits are now OK, thanks for code checking automations.
I had a question, how did you integrate pylint?

**Comment by cclauss** [comment]
You can click on “Actions” above to see the state if the tests.  I use flake8 as linter, not pylint.
